POST http://localhost:3000/api/just-for-you/post
content-type: application/json

{
  "name": "ASUS FHD Gaming Laptop",
  "price": "$960",
  "image": "/bell-try-to-test-image/gaming-laptop.png"
}

### get
GET http://localhost:3000/api/just-for-you/2


### find all
GET http://localhost:3000/api/just-for-you/

### Delete 
Delete http://localhost:3000/api/just-for-you/delete/2

### Delete all
Delete http://localhost:3000/api/just-for-you/delete-all