POST http://localhost:3000/api/just-for-you/post
content-type: application/json

{
    "name": "LENOVO",
    "price": "2000$"
}


### get
GET http://localhost:3000/api/just-for-you/2


### find all
GET http://localhost:3000/api/just-for-you/

### Delete 
Delete http://localhost:3000/api/just-for-you/delete/2